FROM node:lts-alpine as builder
MAINTAINER dison
WORKDIR /apps/template_h5

COPY docker .

# Global install yarn package manager
#RUN apt-get update && apt-get install -y curl apt-transport-https && \
#    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
#    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
#    apt-get update && apt-get install -y yarn

# RUN npm i --global yarn
RUN yarn config set registry https://registry.npm.taobao.org && \
#    yarn config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g && \
    yarn install && \
    yarn build
#RUN  yarn install && \
#     yarn build


FROM nginx:1.17.10-alpine
WORKDIR /apps/template_h5

COPY .version .version
COPY --from=builder /apps/template_h5/docker/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /apps/template_h5/www /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]