FROM nginx:1.17.10-alpine
WORKDIR /apps/ppapp

COPY .version .version
COPY docker/nginx.default.conf /etc/nginx/conf.d/default.conf
ADD www /apps/template_h5/www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]